[server]
host = "0.0.0.0"
port = 3000

[github]
repo_owner = "Pumpkin-MC"
repo_name = "Pumpkin"
branch = "main"
check_interval = 300  # 检查间隔，秒

[build]
workspace_dir = "./workspace"
binary_name = "pumpkin"
build_timeout = 1800  # 构建超时，秒

[runtime]
restart_delay = 5  # 重启延迟，秒
max_retries = 3

[storage]
data_file = "./data.json"
